# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Flutter-iOSTest' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Flutter-iOSTest

  target 'Flutter-iOSTestTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Flutter-iOSTestUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end

flutter_application_path = '../my_flutter'
eval(File.read(File.join(flutter_application_path, '.ios', 'Flutter', 'podhelper.rb')), binding)
